version: '3.8'

services:
  db:
    image: postgres:15
    container_name: building_energy_pg
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: building_energy
      
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: building_energy_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 18313899771@163.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
